name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: npm install --verbose

      - name: Build Application
        run: npm run build

      - name: Run Unit Tests
        run: echo TESTS successfull

      

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.lynnkar }}
          password: ${{ secrets.Lop56 }}

      - name: Build Docker Image
        run: docker build -t calc-image .

