name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: npm install --verbose

      - name: Build Application
        run: npm run build

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Run Integration Tests
        run: npm run test:integration

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.lynnkar }}
          password: ${{ secrets.Lop56 }}

      - name: Build Docker Image
        run: docker build -t calc-image .

